### ISSUE TITLE
View editing: fetch quickActions after PATCH /edit

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2020] opened 2018-10-19 09:04 UTC
### Is this a bug or feature request?
FR

required for https://github.com/metasfresh/metasfresh/issues/4577#issuecomment-431018536

**Comment by siemiatj** [comment] 2018-10-24 07:47
Well I'm not sure this is still a part of this ticket though. This is caused by how the widgets were architected in the first place, not my last changes. This doesn't break anything so I'd create a separate issue instead.

**Comment by teosarca** [comment] 2018-10-24 08:50
ok, thanks.

**Comment by metas-dh** [comment] 2018-11-08 14:50
Results of IT1
tested in mf15

* quickActions are fetched after PATCH /edit in view (checked in product price & Review modal): OK
* quickActions fetched more than once: OK for now agaiu, see above.

**Closed by metas-dh** 2018-11-08 14:50 UTC
Labels: branch:master, branch:release, type:enhancement
