### ISSUE TITLE
Process result: implement openDocument as modal

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#676] opened 2017-04-24 15:04 UTC
### Type of issue
Feature request

### Current behavior
When frontend is starting a process which returns an "openDocument" action, frontend is opening that document in a new browser tab.

### Expected behavior
On "openDocument" action we introduced another field called "modal" (true or false).
If modal:true the document shall be displayed as a modal window (same as HU editor it is now).

### Steps to reproduce
* select a BPartner
* call the "Create request" action
* as a result, the "Create request" returns something like:
![image](https://cloud.githubusercontent.com/assets/1244701/25343664/5afe85a6-2918-11e7-8099-68b6d62b835f.png)

**Comment by teosarca** [comment] 2017-04-24 15:05
Required for https://github.com/metasfresh/metasfresh-webui-api/issues/300

**Comment by Dunkat** [comment] 2017-04-25 06:55
hello, @teosarca how can I call the "Create request" action? Could you please provide steps?

**Comment by teosarca** [comment] 2017-04-25 07:28
Hi @Dunkat 

Simple, go to a partner, e.g. https://w101.metasfresh.com:8443/window/123/2156481
and from action menu call "Create request".

**Comment by teosarca** [comment] 2017-04-26 09:07
As discussed on skype, 
* the backend will provide "advanced" flag in action response
* when opening the modal, pls use the caption from layout

**Comment by teosarca** [comment] 2017-04-26 09:45
pls fix: when the modal is opened it shall use the provided documentId and not "NEW":
![image](https://cloud.githubusercontent.com/assets/1244701/25428311/2a23054e-2a7e-11e7-8358-52dd41f16d86.png)

**Comment by Dunkat** [comment] 2017-04-26 12:44
can't reproduce "NEW" documentId.  Probably fixed by the way, but if you find this, please send me how to reproduce.

**Comment by teosarca** [comment] 2017-04-26 13:11
then let's integrate and see.
in my case, it's happening ALL the time, no magic.

**Comment by teosarca** [comment] 2017-04-26 14:23
test case not working:
* goto BP grid: https://w101.metasfresh.com:8443/window/123
* select a BP, but DO NOT GO TO SINGLE document
* Action menu => create request
=> frontend is getting a NEW document instead of using the given one

**Comment by metas-lc** [comment] 2017-05-02 13:37
- single document / grid view: 
- modal:true
- type:"openDocument"
- instead of NEW it's the documentID OK

questions: 
1. after i create a request i have to refresh the page to see it in request tab. Is it OK?
2. if i create a request while i am in gridview it asks me if i am sure i want to leave the page (when pressing done in modal). OK?

**Closed** 2017-05-02 13:57 UTC
Labels: enhancement, high priority, integrated, release-candidate
