### ISSUE TITLE
Research about resolution for heavy 5000 rows gridviews (window/540345)

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui-frontend#875] opened 2017-06-13 09:56 UTC
### Type of issue
Feature request
### Current behavior
The gridview with >5000 rows is slow.
### Expected behavior
Optimize it / refactor it.
### Steps to reproduce
/window/540345

**Comment by cadavre** [comment] 2017-07-25 09:03
Cannot reproduce anymore. Probably fixed with some other issue. If it is going to happen again – please reopen or create new issue with more info about issue itself.

**Closed** 2017-07-25 09:02 UTC
Labels: type:enhancement
