### ISSUE TITLE
[ctrl]a focus in Grid Fields

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#486] opened 2017-03-04 10:43 UTC
### Type of issue
Feature request
### Current behavior
In Grid view, when selecting all data of a field w/ mouse or w/ [ctrl]a, then the user does not see that the data is marked for overwriting. It seems as if the selection has the same color than the selected line color.
### Expected behavior
Double click in the field should let the user see that the data as "selected all" [ctrl]a for the field. The user then can use the arrows up/ down for change or directly overwrite w/ numbers.
### Steps to reproduce
Can be checked in any grid view w/* editing possibility.
![image](https://cloud.githubusercontent.com/assets/13365687/23578114/b290f446-00cf-11e7-8b92-e8125a9b41a3.png)

**Comment by teosarca** [comment] 2017-03-05 09:59
duplicate of #475

**Closed by teosarca** 2017-03-05 09:59 UTC
Labels: enhancement
