### ISSUE TITLE
number of selected items is missing

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1005] opened 2017-07-11 11:19 UTC
### Type of issue
Bug
### Current behavior
number of selected items is missing

### Expected behavior
should write the number of the items i selected

### Steps to reproduce
(this is in any window / modal)
1. go to sales order (window/143), grid view
2. at the end of the page says "No item selected"OK
3. select 1 ore more lines
=> items selected NOK 
should say e.g. "3 items selected"

![itemsselected](https://user-images.githubusercontent.com/16001666/28065990-c54a1476-6643-11e7-98cb-479f1a1923e2.png)

**Comment by metas-mk** [comment] 2017-07-12 09:09
@cadavre @Dunkat This issue seems not willing to stay away permanently. Has popped up several times until now. Can u please fix again and check what's the reason?

**Comment by cadavre** [comment] 2017-07-12 09:11
It also hit me. After fixing: can author elaborate on?

**Comment by Dunkat** [comment] 2017-07-12 09:59
reason: translations for "view.itemsSelected.caption" misssing, needed be updated by backend, follow: https://github.com/metasfresh/metasfresh-webui-frontend/issues/959#issuecomment-312206470

**Comment by metas-mk** [comment] 2017-07-12 10:08
@Dunkat thanks for the quick info. you're right. the caption translation is added to w101 but not in release yet. so the issue is not a technical one but more an organizational one. I will prepare a full update for the webui messages again.

**Comment by metas-mk** [comment] 2017-07-12 12:41
@Dunkat Found the issue for not updated webui caption and pushes a fix w/ this issue: https://github.com/metasfresh/metasfresh/issues/1929 .

**Comment by metas-mk** [comment] 2017-07-12 12:41
Closing this one.

**Closed by metas-mk** 2017-07-12 12:41 UTC
Labels: priority:high, type:bug
