### ISSUE TITLE
Error when confirm "Create Purchase Orders" action modal

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1483] opened 2018-01-09 09:05 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
When pressing the confirm button in action "Create Purchase Orders" via Sales Order window, an error appears in console.
#### Which are the steps to reproduce?
- Create a new Sales Order and Sales Order line.
- Select the line and start the action "Create Purchase orders".
- Press "Confirm" Button in modal overlay.
- See console.
### What is the expected or desired behavior?
Get rid of the error.

![image](https://user-images.githubusercontent.com/13365687/34712848-8fad7c98-f524-11e7-84fe-311aef9d86fc.png)

![image](https://user-images.githubusercontent.com/13365687/34712822-7ff378ac-f524-11e7-8228-7b2feb6c1158.png)

**Comment by wiadev** [comment] 2018-01-11 17:43
@teosarca I think this is back-end issue.
![screenshot at jan 11 11-41-41](https://user-images.githubusercontent.com/18234060/34838627-788acc5e-f6c4-11e7-879d-57940fcffd37.png)

REQUEST: PATCH http://w101.metasfresh.com:8081/rest/api/documentView/SO2PO/SO2PO-9c0e1fb7a2cd4ac5b7f4950c57dd5b3c/1000521_2156436/edit

PAYLOAD: [{"op":"replace","path":"qtyToPurchase","value":"5"}]

FYI, viewID is returned from URL:http://w101.metasfresh.com:8081/rest/api/process/ADP_540887/1192413/start

**Comment by teosarca** [comment] 2018-01-12 09:06
duplicate of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1361

**Closed by teosarca** 2018-01-12 09:06 UTC
Labels: type:bug
