### ISSUE TITLE
Picking window broken

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1447] opened 2017-12-13 15:03 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently Picking window is broken when picking an HU.
#### Which are the steps to reproduce?
a) Open window https://w101.metasfresh.com:8443/window/540345
b) Select line w/ Convenience Salat and press Pick
![image](https://user-images.githubusercontent.com/13365687/33945178-8d0134e6-e01e-11e7-8534-367a986991a0.png)
c) Select Line on left side. Select Picking Slot 101 on right side and press Open HU Selection Button
![image](https://user-images.githubusercontent.com/13365687/33945231-c3399eae-e01e-11e7-8b6d-293949b4731b.png)
d) Select Palette on right side. Select Pick HU action.
![image](https://user-images.githubusercontent.com/13365687/33945316-f8b673fe-e01e-11e7-8546-7be437229330.png)
e) This happens
![image](https://user-images.githubusercontent.com/13365687/33945335-07d23a62-e01f-11e7-9eab-655e3a921c92.png)
### What is the expected or desired behavior?
Shall work.

**Comment by wiadev** [comment] 2017-12-15 07:54
@teosarca 
The fields are not coming from back-end.
![screenshot at dec 15 01-50-06](https://user-images.githubusercontent.com/18234060/34032222-ad859064-e13a-11e7-990a-4c82d2a66a34.png)
e.g. we need `huQtyCu` field ( one of columns ) from URL:http://w101.metasfresh.com:8081/rest/api/documentView/husToPick/husToPick-2a36b340737241d995990873e596cd86?firstRow=0&pageLength=20.

but `huQtyCu` is not coming from the -back-end.
![screenshot at dec 15 01-51-42](https://user-images.githubusercontent.com/18234060/34032259-cd012624-e13a-11e7-8b9d-7a96cfbdf671.png)

**Comment by teosarca** [comment] 2017-12-15 11:13
@wiadev  hmmm, ok, thanks. will check

**Comment by teosarca** [comment] 2017-12-15 11:27
@wiadev 
On second screenshot u are looking in wrong place.
Remark,
* the layout was fetched for pickingSlot-* view
* so the data shall be for pickingSlot-* view too... not husToPick-*  view.

Might be that's the bug, for some reason, frontend is displaying the data for another windowId.


e.g.
![image](https://user-images.githubusercontent.com/1244701/34040208-6a8aaa18-e19b-11e7-81d1-9b4bf76023b5.png)

![image](https://user-images.githubusercontent.com/1244701/34040275-a30a780a-e19b-11e7-9c35-c5afbcaa8a72.png)

**Comment by wiadev** [comment] 2018-01-11 17:23
@teosarca 
![screenshot at jan 11 11-20-06](https://user-images.githubusercontent.com/18234060/34837770-75f57960-f6c1-11e7-8439-13b606b8de7a.png)

The problem is that husToPick is returned via websocket, again and it's updating the state of pickingSlot's data.

Can you check the backend, please?

**Comment by metas-mk** [comment] 2018-01-12 06:45
Quick check on w101 together w/ @metas-ts 
Websocket: 
```
"MESSAGE↵destination:/view/husToPick-7ba138639ad94caeb884ab1aeb59bc6a↵content-type:application/json;charset=UTF-8↵subscription:sub-0↵message-id:15s3tx3j-52↵content-length:98↵↵{"viewId":"husToPick-7ba138639ad94caeb884ab1aeb59bc6a","windowId":"husToPick","fullyChanged":true}"
Name
```
![image](https://user-images.githubusercontent.com/13365687/34862759-4d55c6d0-f76c-11e7-9452-f76128e040d7.png)

Response Fields (seems as if Picking Slot is missing)
![image](https://user-images.githubusercontent.com/13365687/34862807-87c22174-f76c-11e7-9d62-88bbeb8043ac.png)

**Comment by teosarca** [comment] 2018-01-12 09:01
@wiadev  @metas-mk  @metas-ts  the thing is
Yes, it might be that a websocket event arrived for the previous view.
But the frontend shall ignore it in this case.
I would suggest to do something like: on "view" component level, store which is current viewId. When changing the viewId, store it to that property.
When websocket events are coming, they shall be checked if their viewId it's maching the one from component.

**Comment by teosarca** [comment] 2018-01-15 14:47
**IMPORTANT**: what tobi did on backend side is a workaround to avoid the frontend side problem.
The frontend problem is still there and has to be fixed as I've documented above.

**Comment by metas-lc** [comment] 2018-01-18 15:36
hi. Closing the task as IT went fine, and creating follow-up for the frontend part https://github.com/metasfresh/metasfresh-webui-frontend/issues/1510

**Closed by metas-lc** 2018-01-18 15:36 UTC
Labels: branch:master, priority:high
