### ISSUE TITLE
[alt]++ and [alt]+q not working properly anymore

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1756] opened 2018-04-23 14:11 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
[alt]++ and [alt]+q are not working correctly atm.
#### Which are the steps to reproduce?
* [alt]++
in e.g. sales order: 1st time [alt]++ expands record tab, but 2nd time [alt]++ often has no effect, you have to click somewhere else and then it works again: NOK

* [alt]+q
    * create new sales order, set a bpartner: invoice partner is set, then press [alt]+q: nothing happens, you have to refresh the page or click somewhere else for [alt]+q to open the batch entry: NOK
    * use [alt]+q a second time after it worked: nothing happens, batch entry is not closed: NOK
    * after putting product in quickorderentry and pressing tab and qty = 1 => the action menu is opened as if I pressed Tab +1 NOK
### What is the expected or desired behavior?
Shall work.

**Comment by siemiatj** [comment] 2018-04-24 14:47
@metas-dh As far as I can tell looks like the input fields steal focus. From what I understand it should work independently, no matter if user has cursor in an input, correct ?

**Comment by metas-mk** [comment] 2018-04-25 08:48
@siemiatj Yes, General shortcuts shall work "in window", no matter where the focus is.

**Comment by metasnw** [comment] 2018-04-26 20:35
tested on 5.55.1-9840+master
with webui 5.55.1-1207+master

> after putting product in quickorderentry and pressing tab and qty = 1 => the action menu is opened as if I pressed Tab +1 NOK

Problem still exists. Menu opens (like when you press <Alt>+1 )

**Comment by metas-mk** [comment] 2018-04-27 07:24
> Problem still exists. Menu opens (like when you press +1 )

Cannot reproduce this case. Works for me.

**Comment by metasnw** [comment] 2018-04-27 20:40
![image](https://user-images.githubusercontent.com/16079655/39384126-0677b3f6-4a6c-11e8-8299-7924a63c8ec7.png)

**Comment by metas-mk** [comment] 2018-04-28 12:38
Checked on windows client with up-to date chrome.
Here a case that works properly (action menu [alt]+1 does not open when entering the qty)

![image](https://user-images.githubusercontent.com/13365687/39396612-77bd3056-4af1-11e8-945f-1445b49c6bf8.png)

--> Handle Key Up also shows the Alt key. In the case of @metasnw the Key Up event for Alt is not fired.

**Comment by metasnw** [comment] 2018-04-28 12:49
also found a workaround for me.
when I am entering the product field using the mouse its fine.

**Comment by metas-dh** [comment] 2018-05-02 10:29
similar problems (timing issue as well):

* when you open the actions in bpartner window and select "Create Request", then start writing in the text field, you cannot use any key that's used in a shortcut, e.g. "e" => Advanced Edit is opened;
but only if you work fast, if you take your time and click slowly, step by step, it works fine

* same when using "d" in letter modal, after opening that from order window: you get question if you want to delete the order

**Comment by siemiatj** [comment] 2018-05-02 11:43
I think it's the way we type + our keyboards. I was not able to reproduce this on my mechanical keyboard as I press keys in different order, so that I'm releasing char key BEFORE releasing modifier, like alt. And on my built-in mac keyboard I do the opposite most of the time. Jesus that's a weird one :)

**Comment by siemiatj** [comment] 2018-05-02 11:59
@metas-dh @metas-mk @metasnw Can you guys check again on this `dev-test-shortcuts` branch ?

**Comment by metas-mk** [comment] 2018-05-03 04:46
@siemiatj thanks. looks good now. could not reproduce the describes behavior anymore.

**Comment by metas-lc** [comment] 2018-05-15 12:53
IT
1. sales order: 1st time [alt]++ expands record tab, 2nd time [alt]++collapses OK
2. alt+q => opens and closes batch entry (tried after adding bpartner and randomly) OK
3. adding a product in batch entry: alt+q add product press tab, tab, 1 enter
=> product is added on the line, actions menu did not open OK
4. using create request in bpartner => writing e won't open adv. edit. OK
5. using alt+r to create a letter in order => writing e or d or any other letter won't open adv. edit or delete /and so on. OK


Other shortcuts:
1. alt+e (advance edit) is working in headers, but only if you are in a field. OK?
2. alt+w, alt+n, alt+r, alt+k, alt+p, alt+d, alt+i are working fine OK
3. alt+3/4/5/6 are working (inbox, menu and sidelist open), but when you press it again, they are not closing OK?

noticed: when you are in e.g. letter (alt+r) and press alt+d, delete popup appears in the background OK?

**Comment by metas-lc** [comment] 2018-05-24 12:05
created follow-up: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1808

**Closed by metas-lc** 2018-05-24 12:05 UTC
Labels: branch:master, branch:release, priority:high, status:waiting-for-feedback, type:bug
