### ISSUE TITLE
Document Line Delete Behaviour

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#588] opened 2017-03-29 11:57 UTC
### Type of issue
*  Feature request
### Current behavior
* When a document line ( e.g. Purcahse Order line) is deleted it still appears in the list even if it doesn't exist any more.
### Expected behavior
* The line should also dissapear from the lines list.
### Steps to reproduce
* Create a purchase order, add a line for it, delete the line.
* => NOK: The line was deleted but it still appears in the list
* After refresh the line dissapears.

The backend shall transmit to the frontend that the line was deleted and the frontend shall update accordingly ( line to be deleted from the list).

This task has this https://github.com/metasfresh/metasfresh-webui-api/issues/272 as backend counterpart.

**Comment by teosarca** [comment] 2017-03-29 15:08
UPDATE: Deleted documents are not communicated to frontend. e.g.

![image](https://cloud.githubusercontent.com/assets/1244701/24461736/b819552c-14aa-11e7-9cf3-a2e74c28cde7.png)

**Comment by damianprzygodzki** [comment] 2017-03-30 09:52
I have a bit problem to understand what is expected behavior. Now, when we delete line in order i.e, it disappearing immediately. For what is that property `deleted`?

**Comment by teosarca** [comment] 2017-03-30 11:23
In my tests i found out that in some cases (as document here) the line is simply not deleted from frontend even though it was deleted on backend side.

I think the issue was introduced by the recent changes where we comunicate the saveStatus/validStatus on header document and included documents.

To make it clear/obvious for frontend now we are communicating back which were the documents which were deleted (basically the ones from the request).

**Comment by teosarca** [comment] 2017-03-30 11:24
note: Lili ( @metas-lc ) will try to reproduce it again and will provide steps to reproduce.

**Comment by damianprzygodzki** [comment] 2017-03-30 11:30
Okay, in my opinion deleted property is not a way to decide if frontend should delete row, because in that moment it should be gone already. Rows after deletion should be deleted automatically, everytime, without any logic.

Please provide steps to reproduce frontend issue when rows are not removed properly.

**Comment by cadavre** [comment] 2017-03-30 11:31
Eventually, if relying on "deleted" flag we would must add "disabled" state to row for a moment when frontend is waiting for API response. It would must disable all possible actions on that row.

**Comment by damianprzygodzki** [comment] 2017-03-30 11:33
@cadavre but then, we should go 100% on deletion from API. We always had other approach.

**Comment by metas-lc** [comment] 2017-03-30 11:36
Couldn't reproduce. When i delete an orderline (saved or not) the line is removed instantly

**Comment by metas-mk** [comment] 2017-04-05 09:00
Closing for now. When it pops up again, then open a new task.

**Closed by metas-mk** 2017-04-05 09:00 UTC
Labels: enhancement, high priority, metasfresh turn
