### ISSUE TITLE
Fix the scrollbars when having an overlay grid view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#311] opened 2017-02-15 16:13 UTC
(see screenshot)
1. totally pointless because we have 2.
2. yup, we need to keep it
3. hide it, there is no need for it and also looks ugly.

![image](https://cloud.githubusercontent.com/assets/1244701/22983265/44b2102c-f3aa-11e6-8163-a5ea9734cc83.png)

**Comment by chmieludaniel** [comment] 2017-02-16 14:41
Cannot reproduce in proper view, due to server error.

**Comment by teosarca** [comment] 2017-02-16 16:37
pls try again

**Comment by damianprzygodzki** [comment] 2017-02-17 09:00
@chmieludaniel The 2nd one problem is solved by #313. The 3rd one should be probably fixed in componentDidMount in RawModal.

**Comment by metas-mk** [comment] 2017-02-20 14:50
Tested. "The evil scrollbar" ;-) w/ Full HD resolution is now back again.
![image](https://cloud.githubusercontent.com/assets/13365687/23129753/3287e92a-f784-11e6-8881-5f5d5f5f0fed.png)

**Comment by metas-lc** [comment] 2017-02-21 07:25
IT
1. horizontal scrollbar appears if not enough space, disappears if enough.
2. exterior vertical scrollbar is there all the time (the one for attributes)
3. interior vertical scrollbar is visible only when needed (e.g. havng lots of LUs) 
4. there is no third vertical scrollbar

**Closed** 2017-02-21 07:33 UTC
Labels: bug, integrated, IT failed, UX
