### ISSUE TITLE
Shortcut usage when focus in field

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#269] opened 2017-02-11 13:04 UTC
Scenario: User opens batch input in Sales Order Window. Focus set to the first field. Starts writing, recognizes that Pricelist in the header is missing. Wants to quickly collapse batch entry. Not possible without pressing <tab> 5-6 times in chrome.
What about allowing <esc> to quickly loose field focus and then able to use global shortcuts?

![image](https://cloud.githubusercontent.com/assets/13365687/22853931/8aedd72e-f062-11e6-90c8-80b785a23f1c.png)

**Comment by cadavre** [comment] 2017-02-13 10:21
Duplicate of #214

**Closed by cadavre** 2017-02-13 10:21 UTC
Labels: enhancement
