### ISSUE TITLE
sitemap: menu item incorrectly flagged as favorite in search result

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#966] opened 2017-07-02 20:25 UTC
### Type of issue
Bug

### Steps to reproduce
* open sitemap: https://w101.metasfresh.com:8443/sitemap
* search for something which you know is not already flagged as favorite. In my case i've searched for "user".
* remark that the second menu item is flagged as "favorite" even if API answered that it's not. => NOK
* more, i did some other searches and in my case i've observed that ALWAYS the second menu item is flagged as favorite, no matter what.

![image](https://user-images.githubusercontent.com/1244701/27773196-196a3964-5f7d-11e7-9eea-861918dc65ee.png)

----
Additionally, after i search for something,
if i want to mark as favorite one of the items that i've found,
after i click, the search result is reset and now it's showing me the whole menu => NOK: the search result shall stay.
![image](https://user-images.githubusercontent.com/1244701/27773213-a79749c0-5f7d-11e7-8b1f-ad41844fa8e5.png)

**Comment by Dunkat** [comment] 2017-07-05 12:49
can't reproduce 1. searching for 'user' -> user is not mark as favourite

**Comment by teosarca** [comment] 2017-07-11 09:59
rolled to w101

**Comment by metas-rc** [comment] 2017-07-13 09:14
Results of IT

Tested on webui

The problems described are solved.
Each time an item is marked / unmarked as favorite the inspection shows it with the right status.
The items are shown as favorite only if they really are marked as favorite.
Search works correctly even after marking one founf item as favorite

**Closed by metas-rc** 2017-07-13 09:14 UTC
Labels: branch:master, type:bug
