### ISSUE TITLE
Search field in Pricing conditions - keyboard selection

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1785] opened 2018-05-10 10:41 UTC
### Is this a bug or feature request?
bug
follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1765
### What is the current behavior?
cannot select an entry using the keyboard
#### Which are the steps to reproduce?
1. go to ales order, create a new one, add a product. Select the line, go to actions and start Pricing Conditions
2. write smth in payment term  (e.g. press SPACE)
=> list with entries 
3. try to use down arrow to select an entry
=> the second row is selected instead NOK
### What is the expected or desired behavior?
the entries in the list should be selected

**Comment by siemiatj** [comment] 2018-05-24 10:44
Can't really reproduce this. It may be because I turned off the default edit state for all editable fields.  I opened the pricing conditions, selected the field, pressed enter and then changed options with keyboard arrows.

![errooo](https://user-images.githubusercontent.com/513460/40480897-1881f3c4-5f50-11e8-8841-579b59b41f0c.gif)

**Comment by metas-lc** [comment] 2018-06-06 11:25
Please try the same testcase, but instead of Type, use Payment Term (seems it;s happening on search fields)
if you have something in Payment Term press x and then press space and down arrow
=> it moves to next fields
![image](https://user-images.githubusercontent.com/16001666/41035425-47801030-6995-11e8-82f5-75f46b66f30d.png)

**Comment by metas-lc** [comment] 2018-07-17 08:08
IT
When i double click on Payment Term, the first field is selected. I can select the column and start writing, but if i select the scrollbar to get back to it, i have to double click again and i get back to the first field
http://recordit.co/zXJIKJvo8i
happens the same with other fields, but not exactly the same way: you e.g. double click on payment discount, and right after select the next field => jumps
.
checked search fields in other places: Product window, tab CU_TU allocations. If you start searching in a search field, you cannot close it by moving to other fields
![image](https://user-images.githubusercontent.com/16001666/42804184-e027ae5c-89b0-11e8-9534-54eb76fe78ed.png)
.
jumping also happens in other places: included tabs: see business partner window, change things in Customer tab. 
Same: product price window (540325), you can edit prices there with right click. If you select a field near, jumps.
.
in headers (e.g. product price window) search fields seem fine

**Comment by siemiatj** [comment] 2018-07-18 14:13
It is related. I think it's because I wanted to have focus on the table after closing the dropdown. But apparently I was too aggressive with this ;)

**Comment by metas-dh** [comment] 2018-07-23 10:56
had the same problem like in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1785#issuecomment-405497189 in e2e, in window/53009:
* e.g. field bpartner, press space bar: all bpartners are available for selection, OK
* click somewhere else: results from that field remain displayed, NOK

![2018-07-23 12_55_42-metasfresh](https://user-images.githubusercontent.com/18696715/43072861-d805d016-8e77-11e8-9e08-e064bec7cea3.png)

**Comment by metas-lc** [comment] 2018-07-24 13:45
IT
- it's not jumping anymore when you double click on field, or you select the field nearby. OK
- the first issue is back: write " " (space) in paymentterm from Pricing conditions, use down arrow to select one - the row under is selected NOK
- when you use a search field and you don't select anything, the field is not closing when you move to another (see pic above) NOK

**Comment by siemiatj** [comment] 2018-07-24 21:40
Any ideas if this was tested after #1886 was merged ?

**Comment by metas-lc** [comment] 2018-07-25 12:42
to be sure, i'll retest it after the next rollout. Taking it back

**Comment by metas-lc** [comment] 2018-07-25 16:05
checked: http://recordit.co/uo3jshHR4M
it jumps on pressing down arrow

and the problem with search fields remaining open when you don't select anything is also still there

**Comment by metas-lc** [comment] 2018-08-08 15:54
IT
1. go to ales order, create a new one, add a product. Select the line, go to actions and start Pricing Conditions
2. write smth in payment term (e.g. press SPACE)
=> list with entries
3. try to use down arrow to select an entry
=> works OK
4. remove what you selected, press space and use down arrow to select another entry
=> the second row is selected instead NOK
.
5. checked jumping in grid view
=> no jumping OK
.
6. checked search fields if are being closed
=> are closing when you select other field/ outside OK
.

**Comment by metas-dh** [comment] 2018-09-25 07:06
Results of IT3
tested in release

checked the testcases described above in latest e2e: all worked fine, OK

**Closed by metas-dh** 2018-09-25 07:06 UTC
Labels: branch:master, branch:release, type:bug
