### ISSUE TITLE
Cannot copy text unless it is doubleclicked

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh-webui-frontend#2254] opened 2019-04-25 10:04 UTC
### Is this a bug or feature request?
bug

window: http://localhost:3000/window/108/2188223

1. Goto AD_User window, authentication token tab, click add new token
![image](https://user-images.githubusercontent.com/4482210/56725723-12b1c780-6756-11e9-97a5-5f446b41af82.png)

- when i double click the text i can right click and copy the text, or press ctrl +c and paste somewhere else.
 -> ok

2. when i select the whole text by clicking at the beginning of the token, select the text until the end -- when i right click the selected text i cannot copy it (there's no option) and ctrl+C, ctrl+v doesn't work either.

![GEdAJOPKW9](https://user-images.githubusercontent.com/4482210/56728027-8d7ce180-675a-11e9-81b3-15b5c76f5d64.gif)

**Comment by ionut-movila** [comment] 2019-05-15 13:50
Maybe this is just a matter of how we select the text and where we right-click to show the menu with copy option. 

What I tested:
1. Double click to select whole token and then you can use ctrl+c to copy or right click menu, but please be very careful when you open right click menu so the text will remain selected, you need to click on the token text and not outside because that will cause it to deselect (this is standard browser behaviour)
2. Select the text manually, works either way with right click menu or ctrl+c but same rules apply: make sure text is still selected when pressing ctrl+c or make sure you right click on the text itself this way text will not get unselected.

@TheBestPessimist Please re-test and if all good close this issue.

**Comment by ionut-movila** [comment] 2019-05-15 14:10
Maybe a more elegant solution can be to add a copy button, that will spare us from all the confusion regarding text selection and where to right-click.

**Comment by TheBestPessimist** [comment] 2019-05-15 16:20
>  you need to click on the token text and not outside because that will cause it to deselect (this is standard browser behaviour)
> but same rules apply: make sure text is still selected when pressing ctrl+c or make sure you right click on the text itself this way text will not get unselected.

That's exactly what i did in my example gif. In both times it can be seen that the text is selected when i try to copy/paste it.

Plus, this selection issue could also be related to https://github.com/metasfresh/metasfresh-webui-frontend/issues/2254

**Comment by ionut-movila** [comment] 2019-05-22 09:28
@TheBestPessimist Attaching here the results on our end: http://recordit.co/kVTPRQ5htm

Can't reproduce the issue so far. Tested on Chrome version 74.0.3729.157 on macOS 10.13.6. App running from branch master.

**Comment by TheBestPessimist** [comment] 2019-05-22 10:16
Yep, it seems to be working now for me as well  Chrome 74.0.3729.157 (Official Build) (64-bit) windows.

We can just close this issue since it's working.

**Comment by ionut-movila** [comment] 2019-05-22 10:27
All great, closing it.

**Closed by ionut-movila** 2019-05-22 10:27 UTC
Labels: status:waiting-for-feedback
