### ISSUE TITLE
New widget for date filtering

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1387] opened 2017-11-27 13:38 UTC
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, when the user wants to browse through dates, then the current date-range filter must be used.
In some cases this is not handy at all... to many clicks.

### What is the expected or desired behavior?
Take following example: https://w101.metasfresh.com:8443/window/540253
![image](https://user-images.githubusercontent.com/1244701/33309027-70dac3ea-d425-11e7-9efd-c018799b5140.png)

Remark:
* the filter is "frequent:true" (so it will be displayed directly on view page and not inside the Filters button dropdown)
* the filter has only one parameter
* the parameter has set "showIncrementDecrementButtons:true"
* the parameter has set "widgetType:Date" or "widgetType:DateTime"

=> Those are the conditions to identify that we are dealing with a different filtering widget.

In this case, the frontend shall:
* the caption shall display the current date instead of "Filters: Date", so the user knows on which date he/she is filtering
* render the "<" and ">" which will decrement/increment the current date with 1 day. When user is pressing one of the buttons, the frontend shall:
** automatically decrement/increment the date and apply the filter 
** update the caption

Please let me know what do you think.
I am also open to suggestions to change the protocol as long as we deliver the functionality described here.

**Comment by metas-mk** [comment] 2017-11-27 13:56
Needs:
https://github.com/metasfresh/metasfresh-webui-api/issues/705

**Comment by ottosichert** [comment] 2017-11-30 23:55
I implemented the date stepper for date ranges as well, because their `widgetType` is `Date` as well.

Currently clicking on `<` or `>` will move the date range by one day, do you want to keep this behaviour or alternatively move the date range by its own length, i.e.:

![screenshot-2017-12-1 metasfresh](https://user-images.githubusercontent.com/1255508/33461283-0820cb06-d632-11e7-88ba-5d05f8f01dcc.png)

Previous date range: **25.11.2017 - 01.12.2017**
Next date range: **09.12.2017 - 15.12.2017**

**Comment by metas-mk** [comment] 2017-12-01 09:34
moin @ottosichert 
merged, rollout and quick test. 
here a first feedback about it
a) press on filter button and parm for date --> calendar opens in weird, small dropdown instead of showing the caledar as usual
b) the increment/ decrement button dont' seem to have the same height as the filter button itself (a pixel or 2 too small)
![image](https://user-images.githubusercontent.com/13365687/33476702-34c67498-d683-11e7-9346-14a205e2160a.png)

**Comment by ottosichert** [comment] 2017-12-01 09:59
Hi @metas-mk,

a) This issue is separate from this feature and existed before my PR (at af74af751e2b775477d6f730a23f4f7af8991bbc). I will look into it
b) It's actually half a pixel on Firefox (not visible) and one pixel on chrome (visible). I will fix it as well

**Comment by metas-mk** [comment] 2017-12-01 10:01
Thx.
@ottosichert found another one. also just cosmetic. seems as if the gap between 2 filter buttons are now too narrow when w/o decrement/increment buttons.
![image](https://user-images.githubusercontent.com/13365687/33477706-f134ce56-d686-11e7-8205-448c62c1a4db.png)

**Comment by ottosichert** [comment] 2017-12-01 10:11
This issue was introduced by my feature PR, resolving it as well

**Comment by metas-lc** [comment] 2017-12-05 13:35
IT
1. i had to make some configs to test this task: 
(i might need to create a task to have them by default)
went to table window for qtyonhand, column Date => set range filter on N, filter +/- buttons on Y and Filter default Value on NOW
2. opened window /540253
=> there are 2 arrows - height is OK, as big as the filter
3. press on date filter
=> there is no scroll, the date panel fits
=> question: i wonder if we shall move the calendar a bit more to the right, right under the date? And to change the way date appears "2017-12-05T00:00:00.000+01:00"? (i have to ask)
4. press on filter, open calendar, don't change the date, press apply 
=> error: undefined has an invalid date. (don't know if it's task related?)
5. press on < and > arrows
=> date changes accordingly OK
6. navigating back:
i went from Stock Control Purchase window (540253) to sales order (143)
pressed on date filter in sales order => notice a range date filter
directly pressed on back => notice the filter is still shown, name changed, but it's still a range date filter NOK (probably not task related)

**Comment by metas-lc** [comment] 2018-01-09 11:30
Found another problem while testing https://github.com/metasfresh/metasfresh/issues/3275
go to e.g. Purchase order (window/181), select default filter: Date Promised
add a date, set an hour, apply
select the filter again => the date and hour is reset. Shall keep the latest changes
![image](https://user-images.githubusercontent.com/16001666/34718932-40c8d984-f541-11e7-8bc6-4f7306d33b1b.png)

**Comment by wiadev** [comment] 2018-01-17 16:34
@teosarca While I'm working n this task, I figured that we have a timezone issue on both of front-end and back-end.

So I've updated the front-end to send timezone to back-end but back-end can't parse it.

Check out the following screenshot, please.
![screenshot at jan 17 10-32-21](https://user-images.githubusercontent.com/18234060/35054385-079278fa-fb72-11e7-965d-0d172dbc1d37.png)

**Comment by metas-lc** [comment] 2018-01-19 15:07
IT
3. the calendar appears like a tooltip (looks fine for me) and it's right under date OK
4. new error appears NOK

"Failed converting DateDoc's value '2018-01-19T01:00:00+02:00' (class java.lang.String) to class java.util.Date↵ LookupDataSource: null↵ Widget type: Date"

Actually the filter seems to not work anymore because of that error
5. not working because of no.4 NOK
6. could not reproduce OK

. 
about the other problem in purchase order - date promised  => the problem was solved, the filter remembers the date you set BUT i found a weird issue, similar with old step 4
purchase order -> filter -> default -> date promised -> set a date -> important: click in the field of the date (somewhere in the middle of 2018-01-22T00:00:00.000+02:00)
=> 
undefined has an invalid date. NOK

**Comment by wiadev** [comment] 2018-01-19 15:47
@metas-lc 
Regarding 4 and 5, I've already described in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1387#issuecomment-358362282.

@teosarca Can you take a look at it, please?

**Comment by metas-lc** [comment] 2018-01-19 15:51
@wiadev ah yes sry. I didn't see it. I'll create a task for it.

**Comment by metas-lc** [comment] 2018-01-19 15:56
https://github.com/metasfresh/metasfresh-webui-api/issues/796

**Comment by teosarca** [comment] 2018-01-19 23:19
@wiadev  @metas-lc  that's not a backend issue.
The problem is the frontend is no longer respecting the date format.

In console i've found:
```
Caused by: org.adempiere.exceptions.AdempiereException: Failed converting '2018-01-16T00:00:00+02:00' to date.
 Please use following format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX.
 e.g. 2018-01-20T01:17:34.991+02:00
```

So basically, you are no longer including the milliseconds.

**Comment by siemiatj** [comment] 2019-03-28 14:05
@teosarca can we close this one ? Seems to be really old and doesn't look like it's relevant anymore.

**Comment by teosarca** [comment] 2019-03-29 17:24
yup, closing.

**Closed by teosarca** 2019-03-29 17:24 UTC
Labels: branch:master, branch:release, priority:high, status:IT-failed, status:waiting-for-feedback, type:enhancement
