### ISSUE TITLE
Prepare Update to React 16 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1092] opened 2017-07-28 10:04 UTC
### Type of issue
Feature request

### Current behavior
using React 15

### Expected behavior
be ready for 16

**Comment by cadavre** [comment] 2017-07-28 10:15
https://github.com/facebook/react/issues/10294

Most important: read BC and review on required changes on metasfresh-webui-frontend.

**Comment by wiadev** [comment] 2017-07-28 10:27
React 16 is marked with "next" tag, since it has some potential upgrade paths which might cause difficulties.
Still not stable, and not even release. Somewhere between beta and RC.

So it's not couple clicks job to upgrade (has some risks).

Benefits are not quite clear to do immediate update.
I'd suggest to wait until final specs will be available.

**Comment by metasnw** [comment] 2017-07-28 10:56
ok. so lets wait

**Comment by PabloSichert** [comment] 2017-10-03 09:18
React 16 [released](https://reactjs.org/blog/2017/09/26/react-v16.0.html) 🎉.

Upgrade path from `15.5` should be straightforward when no deprecation warnings are apparent.

**Comment by teosarca** [comment] 2017-10-17 10:23
note to IT:
* webui regression needed
* check file attachments

**Comment by PabloSichert** [comment] 2017-10-17 10:29
Addition:
- check that selection in dropdowns works
- check that clicking around in tables works
- check that clicking native controls (inputs, buttons, checkboxes, ...) when they don't expect any action doesn't break the app

**Comment by teosarca** [comment] 2017-10-17 15:55
hi @PabloSichert 

found this issue: go to sitemap: https://w101.metasfresh.com:8443/sitemap
![image](https://user-images.githubusercontent.com/1244701/31675254-c3a7d132-b36c-11e7-9baf-7214d894e6d4.png)

**Comment by PabloSichert** [comment] 2017-10-17 19:47
Also related issue (app not refreshing after getting translation data):

![image](https://user-images.githubusercontent.com/4450694/31685861-c5549c6e-b384-11e7-80bc-76e934026545.png)

**Comment by teosarca** [comment] 2017-12-15 08:05
this task is IN from October and no complains. Moving it to done.

**Closed by teosarca** 2017-12-15 08:05 UTC
Labels: branch:master, branch:release, type:enhancement
