### ISSUE TITLE
Searchresults are missing in Navigation menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#182] opened 2017-01-10 13:40 UTC
Searchresults are missing in Navigation menu

![image](https://cloud.githubusercontent.com/assets/13365687/21808230/9fa02d04-d742-11e6-91f9-902a4c852738.png)

**Comment by damianprzygodzki** [comment] 2017-01-10 14:34
https://github.com/metasfresh/metasfresh-webui-frontend/issues/156 Related, tested, to implementation.

**Comment by cadavre** [comment] 2017-01-12 10:24
I'm closing this due to duplicate of #156 .

**Closed by cadavre** 2017-01-12 10:24 UTC
Labels: bug
