### ISSUE TITLE
Opening a new window or using back button often results in an empty page

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#2032] opened 2018-10-29 15:47 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
Sometimes when you open a new window or use the back button to get to the previous page, that results in an empty page and you have to refresh.

console:

<details>

```
popper.js:25 Uncaught TypeError: Cannot read property 'indexOf' of null
    at t.value [as handleClick] (popper.js:25)
    at onClick (popper.js:25)
    at Object.<anonymous> (react-dom.production.min.js:13)
    at f (react-dom.production.min.js:13)
    at react-dom.production.min.js:13
    at E (react-dom.production.min.js:13)
    at S (react-dom.production.min.js:13)
    at D (react-dom.production.min.js:13)
    at M (react-dom.production.min.js:13)
    at j (react-dom.production.min.js:13)
value @ popper.js:25
onClick @ popper.js:25
(anonymous) @ react-dom.production.min.js:13
f @ react-dom.production.min.js:13
(anonymous) @ react-dom.production.min.js:13
E @ react-dom.production.min.js:13
S @ react-dom.production.min.js:13
D @ react-dom.production.min.js:13
M @ react-dom.production.min.js:13
j @ react-dom.production.min.js:13
Tn @ react-dom.production.min.js:13
ma @ react-dom.production.min.js:13
Ne @ react-dom.production.min.js:13
Sn @ react-dom.production.min.js:13
ba @ react-dom.production.min.js:13
xn @ react-dom.production.min.js:13
react-dom.production.min.js:13 TypeError: k.indexOf is not a function
    at popper.js:25
    at Array.map (<anonymous>)
    at t.value [as renderTableBody] (popper.js:25)
    at t.value (popper.js:25)
    at Zo (react-dom.production.min.js:13)
    at Ko (react-dom.production.min.js:13)
    at ti (react-dom.production.min.js:13)
    at Di (react-dom.production.min.js:13)
    at Ai (react-dom.production.min.js:13)
    at da (react-dom.production.min.js:13)
```
</details>

Might be similar to the problem fixed here: https://github.com/metasfresh/metasfresh-webui-frontend/pull/2025/commits/8a00f4ace8b45068cb33e7094fbad725b0d5982b
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Shall work.

**Comment by siemiatj** [comment] 2018-10-30 17:33
Looks like a duplicate of #2034

**Comment by teosarca** [comment] 2018-10-31 08:56
quick tested #2034 and works.

**Closed by teosarca** 2018-10-31 08:56 UTC
Labels: type:bug
