### ISSUE TITLE
Filter call missing for special Filters

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1568] opened 2018-02-08 11:08 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, it is not possible to use the special filters. The user receives an empty screen.
#### Which are the steps to reproduce?
- open /window/540165
- Filter first entry. Apply.
Filter is not applied. Seems as if the filter request is missing.
### What is the expected or desired behavior?
The spacial filters shall work.

![image](https://user-images.githubusercontent.com/13365687/35969997-f1057aca-0cc8-11e8-9bcd-1fce14a2d13c.png)

![image](https://user-images.githubusercontent.com/13365687/35969951-d2a6b012-0cc8-11e8-89b2-7e6a21a6ca3d.png)

**Comment by teosarca** [comment] 2018-02-08 11:39
duplicate of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1570

**Closed by teosarca** 2018-02-08 11:39 UTC
Labels: priority:high, type:bug
