### ISSUE TITLE
uniformize hour for date fields

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#472] opened 2017-03-02 17:53 UTC
### Type of issue

Bug

### Current behavior

when adding a date in a date field, it looks like this in Request Payload: "2017-03-03T01:00:00.000+02:00"

### Expected behavior
hour to be 00 
"2017-03-03T00:00:00.000+02:00"

### Steps to reproduce

1. go to sales order and create a new one
2. set another date in Date Ordered field
=> see  Request Payload: you have hour 01. 
in preview is ok  "2017-03-03T00:00:00.000+01:00"

**Link:** https://w101.metasfresh.com:8443/window/143/1004058

![dateordered](https://cloud.githubusercontent.com/assets/16001666/23520031/debebfc0-ff81-11e6-832f-2eeaecb7294f.png)

![dateordered2](https://cloud.githubusercontent.com/assets/16001666/23520035/e4e5f396-ff81-11e6-9889-a91e0ce9659b.png)

**Comment by damianprzygodzki** [comment] 2017-03-27 07:09
Cannot reproduce, expected behavior is exactly what i got.

![screen shot 2017-03-27 at 09 09 12](https://cloud.githubusercontent.com/assets/5701744/24344721/19310ea2-12cd-11e7-84d3-d39fddda1f04.png)

**Comment by cadavre** [comment] 2017-04-19 11:58
@metas-lc can you please check one more time and if all fine – close issue. If not – please provide more info to reproduce.

**Comment by metas-lc** [comment] 2017-04-19 12:40
@cadavre hi. I can still reproduce it. I think it's related with my timezone..
created sales order window/143/1005053. Add all mandatory fields
changed date ordered from 19.04 to 17.04
i have this in headers: 0:{op: "replace", path: "DateOrdered", value: "2017-04-17T01:00:00.000+03:00"}
and this in preview: {field: "DateOrdered", value: "2017-04-17T00:00:00.000+02:00", widgetType: "Date",…}


![so1](https://cloud.githubusercontent.com/assets/16001666/25180295/195dd0a8-2516-11e7-96b9-edf398ef2544.png)

![so2](https://cloud.githubusercontent.com/assets/16001666/25180299/1b289da0-2516-11e7-85af-c8db3f53c1af.png)

**Comment by cadavre** [comment] 2017-04-19 12:47
`2017-04-17T01:00:00.000+03:00`
vs
`2017-04-17T00:00:00.000+02:00`

Looks good because hour changed but also timezone too!

Does this affect what you shall see in UI? Or just APIs calls? Because API communication is just fine.

**Comment by cadavre** [comment] 2017-04-19 12:51
Duplicate of #471 .

**Closed by cadavre** 2017-04-19 12:51 UTC
Labels: bug, metasfresh turn
