### ISSUE TITLE
automatic Column sizing not showing all text although space would be available

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#772] opened 2017-05-22 07:33 UTC
### Type of issue
Feature Request
### Current behavior
![image](https://cloud.githubusercontent.com/assets/16079655/26297002/6524832c-3ed1-11e7-9acb-173403bb905c.png)

### Expected behavior
If other columns have enough space shrink them and use the space to show other columns whose data is cut off

### Steps to reproduce
https://w101.metasfresh.com:8443/window/123/2156481

compare column Type and Created by (erstellt durch)

### Severity
Two cases are currently known and there is no workaround:
1. request type names which are widely used in CRM
2. product name in order line

**Comment by damianprzygodzki** [comment] 2017-05-22 08:35
Duplicate of https://github.com/metasfresh/metasfresh-webui-frontend/issues/217

**Comment by metasnw** [comment] 2017-05-22 09:26
@damianprzygodzki 
to me it seems to be in the same area but comparing the screenshots of both issues it seems to be a different problem.
If you can solve both with the same fix I am fine but this one is actually causing problems at different users and need to be addressed.

Ideas: 
1. use content of cell to determine the column size
2. provide a workaroud like mouse over to allow the user to see the content of the field

**Comment by cadavre** [comment] 2017-05-22 15:13
It actually is same issue as in #217 but still waiting for response there. There is now way we can determine column widths based on content while they have their own priorities. This would need some additional control on backend side.

**Comment by metasnw** [comment] 2017-05-22 15:14
is this because you do not know its content?

**Comment by metas-mk** [comment] 2017-05-23 09:41
Discussed in Jour Fix.
Provide the size override for window & column layout if different for the given window: S, M, L

**Comment by damianprzygodzki** [comment] 2017-05-23 09:44
lg = 225px
md = 100px
60px  < sm <100px

**Comment by teosarca** [comment] 2017-05-23 11:00
In "element", i think we shall introduce an optional property called "width" which can be S, M , L.
fine for u?

**Comment by damianprzygodzki** [comment] 2017-05-23 11:29
maybe `size` would be better, because it is not actually width.

**Comment by teosarca** [comment] 2017-05-23 12:25
yup, size it's also OK for me. 
So pls, let's go with the "size".

NOTE: atm backend is not providing this property so you would need to mock it while dev-testing.

**Comment by metas-mk** [comment] 2017-05-25 11:06
Tested. Works nicely with current data. Done, closing.

**Closed by metas-mk** 2017-05-25 11:06 UTC
Labels: release:candidate, status:integrated, type:enhancement
