### ISSUE TITLE
Opening a new included view is broken (again)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1258] opened 2017-10-14 09:10 UTC
see https://github.com/metasfresh/metasfresh-webui-frontend/issues/1243

**Comment by teosarca** [comment] 2017-10-14 09:23
After pressing the "Open HU Selection..." action, nothing happens even though the HU's view layout and data is fetched (windowId=540189).

![image](https://user-images.githubusercontent.com/1244701/31574537-6e6a5bac-b0da-11e7-8411-dcb64b0a8306.png)

**Comment by ottosichert** [comment] 2017-10-16 16:57
**Note:** This will most likely conflict with https://github.com/metasfresh/metasfresh-webui-frontend/pull/1264 (same as https://github.com/metasfresh/metasfresh-webui-frontend/issues/1263#issuecomment-336951440)

**Comment by metas-lc** [comment] 2017-10-20 10:36
IT
1. go to picking slots window, select a line, pick
2. select a picking slots, open hu selection window
=> included view opens OK
3. select an hu and press on pick HU
=> only once, i got this (see pic), rest of the time i could see the picking slots, but for a very short time, like 0.5s i could see like in pic
![image](https://user-images.githubusercontent.com/16001666/31817129-6bf2fada-b59b-11e7-8e01-79d84c0314e6.png)

**Comment by ottosichert** [comment] 2017-10-20 11:25
See my comment in PR https://github.com/metasfresh/metasfresh-webui-frontend/pull/1282#issuecomment-338007949. I am still waiting for feedback on this one, but I assume this should work...

> I tried following steps:
> 
> - Open **Picking Terminal** (https://w101.metasfresh.com:8443/window/540345)
> - Select first item
> - Click quick action `Pick`
> - Modal opens
> - First item in table and includedView is already selected
> - Click quick action `Open HU selection window`
> - Select a TU in new includedView
> - `Uncaught Error: InvalidStateError: The connection has not been established yet`
> 
> _I this supposed to work?_
> 
> - Open **Picking Terminal** (https://w101.metasfresh.com:8443/window/540345)
> - Select first item
> - Click quick action `Pick`
> - Modal opens
> - First item in table and includedView is already selected
> - Click drop down of quick actions
> - Click `Pick to new HU`
> - Select item in `Packvorschrift-Produkt Zuordnung`
> - Click `Start`
> - Selected item appears below item in includedView
> 
> _Is this correct?_

**Comment by metas-lc** [comment] 2017-10-23 14:25
IT
checked on w101 and it works fine. 
Can you please take a look here as well? 
https://mf15cloudit/window/540345?viewId=540345-dcc1b993d93c4148a3ac3d4531043acb&page=1
it's the only place where is happening and i don't know why
somehow, after you pick, the selected id is for picking slot (ok), but right after the Hu i already picked is selected again and i get empty HUs
steps:
1. open picking, select a line, use Pick:
![picking1](https://user-images.githubusercontent.com/16001666/31894367-ec801c46-b816-11e7-8cfa-eb93c48ae60f.png)
2. open hu selection window: 
![picking2](https://user-images.githubusercontent.com/16001666/31894371-eed164d2-b816-11e7-8d7d-3a430026c863.png)
3. pick HU
![picking3](https://user-images.githubusercontent.com/16001666/31894375-f1345bd0-b816-11e7-8ebe-bc3db412a88d.png)
4. result:
![picking4](https://user-images.githubusercontent.com/16001666/31894378-f2872a12-b816-11e7-876c-78fa4847f0b2.png)

**Comment by ottosichert** [comment] 2017-10-29 12:51
@metas-lc I cannot reproduce this issue.

This is what I get when I follow your steps:
1. open picking, select a line, use Pick
2. open hu selection window
3. pick HU
4. result:
   I get back to the same screen as your step 1:
   ![picking1](https://user-images.githubusercontent.com/16001666/31894367-ec801c46-b816-11e7-8cfa-eb93c48ae60f.png)
   My network requests (**different from your network requests!**):
   ![bildschirmfoto vom 2017-10-29 13-39-51](https://user-images.githubusercontent.com/1255508/32143757-b9280678-bcae-11e7-9585-394c166a6e1e.png)

**Comment by teosarca** [comment] 2017-10-30 13:31
weird, i've also checked using frontend(latest master) running on my laptop but connecting to mf15cloudit and works.
![image](https://user-images.githubusercontent.com/1244701/32173363-6a8f2af8-bd87-11e7-850a-066724c932b5.png)

**Comment by metas-lc** [comment] 2017-10-30 13:48
i'll close this task, since it's not a dev issue. I'll keep an eye on it.

**Closed by metas-lc** 2017-10-30 13:48 UTC
Labels: branch:master, branch:release, priority:high, status:IT-failed, type:bug

**Comment by ottosichert** [comment] 2017-11-05 17:34
When I was working on the first PR (#1282), I had the same issue as you mentioned in your first comment (https://github.com/metasfresh/metasfresh-webui-frontend/issues/1258#issuecomment-338170948) and showed us on your screenshot.

Now my network requests for this process were different than yours and I don't know about @teosarca's setup.

So just a note if this can be reproduced in the future: It might be a race condition regarding network acitivity
