### ISSUE TITLE
Show multiple lines of a multi line text field in grid tab

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1908] opened 2018-08-01 14:54 UTC
### Is this a bug or feature request?
FR

### What is the current behavior?
we always show only one line

#### Which are the steps to reproduce?
- add a request with description with 3 lines 
- open partner window and open request tab
- look add field summary

### What is the expected or desired behavior?
make it configurable how many lines we show per tab or field

**Comment by siemiatj** [comment] 2018-08-24 07:37
Related to #1805

**Comment by teosarca** [comment] 2018-08-30 13:08
@siemiatj  now, in element we have`multilineText` and `multilineTextLines`,
e.g.
https://github.com/metasfresh/metasfresh-webui-api/issues/1032#issuecomment-417278516

**Comment by teosarca** [comment] 2018-08-30 13:08
test case available on w101:
![image](https://user-images.githubusercontent.com/1244701/44853580-fca74200-ac6e-11e8-86c8-3ba497c307ce.png)

**Comment by metas-dh** [comment] 2018-09-13 09:55
Results of IT1
tested in mf15

tested together with https://github.com/metasfresh/metasfresh-webui-api/issues/1032

1. Set multilineText and multilineTextLines properties for Request Tab in bpartner window
2. Checked in frontend if multilineText and multilineTextLines are correctly set in layout: **OK**
3. Created a request with multilines and checked in bpartner window, Request Tab:
=> multilines were not displayed, only when mouse over: **NOK**

![2018-09-13 11_49_10-metasfresh](https://user-images.githubusercontent.com/18696715/45481379-ac8aae00-b74b-11e8-89b6-51446a55f69b.png)

**Comment by siemiatj** [comment] 2018-09-21 15:40
How do I reproduce this failing case ?

**Comment by metas-dh** [comment] 2018-09-27 08:41
Afais you have the multilineText and multilineTextLines properties set in w101, in https://w101.metasfresh.com:8443/window/143 for the product description field:

![2018-09-27 10_39_04-metasfresh](https://user-images.githubusercontent.com/18696715/46133837-bfb87600-c241-11e8-8688-558fdd705219.png)

**Comment by siemiatj** [comment] 2018-09-28 07:38
@metas-dh  It should work differently ? http://recordit.co/qXEKJksWdd

**Comment by metas-dh** [comment] 2018-09-28 13:02
@siemiatj  no, sorry, it obv. should work like that, but i did not read all the info in the relating tasks, just took the 1st info from the original task where it said all the info shall be visible "at first glance" and therefore thought it was NOK.
since it's working fine, i'm moving this to Done.

**Closed** 2018-09-28 13:02 UTC
Labels: branch:master, branch:release, type:enhancement
