### ISSUE TITLE
Cursor Jump in Text Field

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#552] opened 2017-03-18 18:24 UTC
### Type of issue
Bug
### Current behavior
When editing a Text Field (here in Warehouse Advanced Edit Window), and you move the cursor to the middle of the already recorded string and then press a key, then that 1 key is typed, but the cursor jumps to the end of the string again.
### Expected behavior
Don't jump in such cases.
### Steps to reproduce
See behavior.
**Window:** /window/139/

![image](https://cloud.githubusercontent.com/assets/13365687/24074827/7e16b5c4-0c10-11e7-84de-d17bdbdb1d27.png)

**Comment by teosarca** [comment] 2017-03-18 18:27
duplicate of https://github.com/metasfresh/metasfresh-webui-frontend/issues/474

**Closed by teosarca** 2017-03-18 18:27 UTC
Labels: bug
