### ISSUE TITLE
Special Place for Record dependent content

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#88] opened 2016-11-09 14:26 UTC
Idea to sharpen the area for record dependant content in WebUI:

- Instead of having it mixed up with actions in action menu
- have a sticky note/ tab on right side in detailed view only if content is available, In there one can see the references and attachments for this record. Also archived documentns.

Just a first, rough idea for now.

**Comment by cadavre** [comment] 2016-11-09 14:49
+1 for this

**Comment by damianprzygodzki** [comment] 2017-03-27 12:09
Isn't it related to #98? Lot of things in plans there, we also have sidelist too on the right side.

**Comment by cadavre** [comment] 2017-03-30 08:32
I'm on with mockups.

**Comment by damianprzygodzki** [comment] 2017-04-25 08:46
Can we close this? It looks like duplicate of #267 which is closed.

**Comment by cadavre** [comment] 2017-04-25 08:47
@damianprzygodzki true, closing.

**Closed by cadavre** 2017-04-25 08:47 UTC
Labels: integrated, new feature, release-candidate, UX
