### ISSUE TITLE
included row: typeahead and dropdown endpoints are wrongly called

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#813] opened 2017-05-31 07:57 UTC
### Type of issue
Bug

### Steps to reproduce
* create a new sales order
* Add a new line
* start typing something in Product field => ERROR

remark that the endpoint is wrongly called, i.e. the rowId is missing...

![image](https://cloud.githubusercontent.com/assets/1244701/26621569/e41da95e-45ef-11e7-8d89-173b8c613eb4.png)

Issue introduced by https://github.com/metasfresh/metasfresh-webui-frontend/issues/787

**Comment by damianprzygodzki** [comment] 2017-05-31 10:53
`Lookups` fixed, can't reproduce issue with `Lists`

**Comment by metas-mk** [comment] 2017-05-31 13:36
Tested. Works as required. Closing.

**Closed by metas-mk** 2017-05-31 13:36 UTC
Labels: branch:master, priority:high, type:bug
