### ISSUE TITLE
Image widget might generate considerable traffic

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#934] opened 2017-06-22 19:31 UTC
### Current behavior
Image for image widget is fetched using [GET /rest/api/image/{imageId}](http://w101.metasfresh.com:8081/swagger-ui.html#!/image-rest-controller/getImageUsingGET) without any of maxWidth or maxHeight parameters.

This can generate a lot of traffic because the image is provided in it's original size.

### Expected behavior
Please provide maxWidth or maxHeight closer to what you need.

### Steps to reproduce
Just open your profile and consider that you have uploaded some big avatar.
![image](https://user-images.githubusercontent.com/1244701/27452193-6a06175c-579a-11e7-8e05-78a0b2f0f0eb.png)

**Comment by metas-mk** [comment] 2017-06-28 14:11
Tested.
a) Uploading Avatar Foto automatically limiting to size 200x200. OK
b) Taking a webcam Foto for the Quality Inspection in Material receipt. Size is also limited to 200x200. That's not enough for a Foto in Quality Assurance. NOK

![image](https://user-images.githubusercontent.com/13365687/27641536-74122098-5c1c-11e7-929c-63e55de68fe1.png)

**Comment by damianprzygodzki** [comment] 2017-06-29 06:15
> This can generate a lot of traffic because the image is provided in it's original size.

This is what the issue is - on one hand you need original size, on other hand you need small size. This is one widget, one image, one size. I said long time ago that sizing should be made by API side, because you know context.

And second thing - it is not limiting size of uploading image - only limiting size of thumbnail.

**Comment by metas-mk** [comment] 2017-06-29 06:24
@teosarca Thanks for the explanation and reproducing via skype talk. Closing/ Done.

**Closed by metas-mk** 2017-06-29 06:24 UTC
Labels: branch:master, status:metasfresh-turn, type:enhancement
