### ISSUE TITLE
Infinite error loop

### ISSUE THREAD

**Issue by tomaszfryc** [metasfresh/metasfresh-webui-frontend#496] opened 2017-03-06 10:22 UTC
### Type of issue
Bug
### Current behavior
When I click "Add new" in "Auftragsposition" with empty fields, then I see infinite error loop.
### Expected behavior
Show one error.
### Steps to reproduce

**Window:** 
MENU(ctrl + 2) -> Neuer Auftrag

**Entity:** 
- click "Add new" in "Auftragsposition",
- wait until error disappear,
- click calendar icon (for example for "Bereitstellungsdatum")
- click again "Add new" in "Auftragsposition"

![zrzut ekranu 2017-03-06 o 11 16 43](https://cloud.githubusercontent.com/assets/26219501/23605874/aedbdede-025e-11e7-9e3a-34e5329be931.png)

**Comment by teosarca** [comment] 2017-03-06 11:50
Might be related to https://github.com/metasfresh/metasfresh-webui-frontend/issues/477

**Comment by damianprzygodzki** [comment] 2017-03-06 16:26
Not reproducible, probably fixed by the way.

**Comment by teosarca** [comment] 2017-03-06 21:16
Happened again but i cannot reproduce it.
What i did was:
* changed the URL to create new
* pressed the sidelist

Take a look at the screenshot below, layout call keeps failing because the windowId is NaN which is not valid.
Wondering, would be easy to check this in frontend and in this case don't repeat on failure.




![image](https://cloud.githubusercontent.com/assets/1244701/23630075/5188e826-02c2-11e7-8a1d-5d4c06c3833b.png)

**Comment by teosarca** [comment] 2017-03-15 13:12
Fixed in #528

**Closed by teosarca** 2017-03-15 13:12 UTC
Labels: bug, integrated, IT failed, release-candidate

**Comment by metas-lc** [comment] 2017-03-15 15:12
IT: 
i could reproduce Teo's case. Will be solved in https://github.com/metasfresh/metasfresh-webui-frontend/issues/528
to retest when it's back in IT
