### ISSUE TITLE
Calling a process from action menu is not working

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#297] opened 2017-02-15 09:11 UTC
Test case:
* open a grid view (e.g. Billing candidates)
* select some rows or don't select anything
* call "Auswahl Fakturieren" (i.e Do invoice)
* u get HTTP 400

Checking the request frontend is sending, the request payload is:
{
documentId:[]
processId:"540304"
}

Which is not ok. See http://w101.metasfresh.com:8081/swagger-ui.html#!/process-rest-controller/createInstanceFromRequestUsingPOST : 
* the documentId is string, and it means "single document id" (to be filled when calling from single document page)
Instead, you have to fill:
* viewId : string
* viewDocumentIds : array

NOTE: see how the process is called from Quick actions. There is OK.

(see screenshot)

Regression tests:
* single document: make sure Action menu -> process call works
* single document: document print works
* grid view: make sure Action menu -> process call works
* grid view: make sure Quick actions -> process call works

![image](https://cloud.githubusercontent.com/assets/1244701/22967537/84cca4dc-f36f-11e6-86aa-2be85cf2c886.png)

**Comment by teosarca** [comment] 2017-02-15 10:17
UPDATE: we have the same issue when calling from Action menu.

test case:
* http://w101.metasfresh.com:8090/window/500221?refType=143&refId=1003648&viewId=f5ef0b3c-fe58-4694-b6fc-bc8495d49ee7&page=1
* call Auswahl... from Action menu
=> wrong IDs!

**Comment by damianprzygodzki** [comment] 2017-02-15 11:36
Tested like:
New Sales Order -> Filled -> Completed -> Lieferungdispo -> Select all -> Auswahl... -> Start -> Success

**Comment by metas-rc** [comment] 2017-02-27 16:13
Results of IT 1: 

tested on https://w101.metasfresh.com:8443

I tested in several windows and got : viewId, viewDocumentIds[]  for grid and DocumentId fors single view. Also, in grid, the viewDocumentIds[] are the correct ones if I select them manually.

But the problem with the wrong IDs when cmoving from a window to another still persists. 

* I opened Material Receipt Candidates and selected a line: 

![wrong id 1](https://cloud.githubusercontent.com/assets/16001442/23368937/3dd1ce60-fd18-11e6-9ca8-5843f1dceb3e.png)


* Then I went to home and opened Sales Orders, and pressed the button for the action menu. NOK: frontend was still sending the ID I selected in the other window: 

![wrong id 2](https://cloud.githubusercontent.com/assets/16001442/23368964/5fefe48c-fd18-11e6-8f2a-34412c60d829.png)




Probably related with https://github.com/metasfresh/metasfresh-webui-frontend/issues/349

**Comment by metas-rc** [comment] 2017-03-01 14:14
Please, check the steps I described here: https://github.com/metasfresh/metasfresh-webui-frontend/issues/349 It is the same situation. 
Note: do not just press on the home button but also press on "Browse whole tree"before moving to another window! The problem is still there.

**Comment by metas-rc** [comment] 2017-03-02 17:14
Please check again. Documented in #349 .

**Comment by metas-lc** [comment] 2017-03-16 13:29
IT:
- single document: make sure Action menu process call works => ok
- single document: document print works => ok
- grid view: make sure Action menu process call works => ok
- grid view: make sure Quick actions process call works => ok
- tested also https://github.com/metasfresh/metasfresh-webui-frontend/issues/349 ok

**Closed by metas-lc** 2017-03-16 13:29 UTC
Labels: bug, high priority, integrated, release-candidate
