### ISSUE TITLE
No Packing Item not selectable in orderline

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1629] opened 2018-02-26 16:20 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
When a packing item is set in orderline, you cannot select No Packing Item anymore, the dropdown does not open.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Shall be possible.

This to me seems quite similar to #1628, if it's the same thing problem pls close this task.

**Comment by siemiatj** [comment] 2018-02-27 01:09
Duplicate of #1628

**Closed by siemiatj** 2018-02-27 01:09 UTC
Labels: type:bug
