### ISSUE TITLE
Tooltip on first level breadcrumb

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#683] opened 2017-04-25 12:50 UTC
### Type of issue
Feature request
### Current behavior
Currently, the breadcrumb navigation does not have a tooltip when hovering.
### Expected behavior
Show a tooltip when hovering w/ the same delay as other tooltips. The tooltip shall describe what the user shall expect when pressing.

![image](https://cloud.githubusercontent.com/assets/13365687/25386110/8b3aff0c-29c6-11e7-8b48-184fdfbeeb98.png)

**Comment by metas-lc** [comment] 2017-05-03 08:09
IT
thre is no tooltip on the first level breadcrumb NOK

**Comment by teosarca** [comment] 2017-05-04 19:40
Quick checked, can u pls hide "the other" tooltips because are pointless?
![image](https://cloud.githubusercontent.com/assets/1244701/25721841/9e488064-311a-11e7-81ef-d3a0feab9c1a.png)

![image](https://cloud.githubusercontent.com/assets/1244701/25721851/a4d3a922-311a-11e7-83c8-2ee771c4bbc3.png)

**Comment by cadavre** [comment] 2017-05-10 07:20
https://github.com/metasfresh/metasfresh-webui-frontend/issues/683#issuecomment-298847540 There's no need for tooltips in any other breadcrumb element than pointed out by Mark in issue description. The only breadcrumb element that changes STATE of window is last clickable – which goes to "documents list", other simply opens overlays which you can simply deactivate.

Please – don't overflow UI with unnecessary elements.

**Comment by metas-lc** [comment] 2017-05-10 15:37
IT
1. sales/ purchase order, hover on the first level breadcrumb
=> tooltip: "Go to default documents list" OK
=> default tooltips are not showing OK
=> (regression) fields still have default tooltip OK
=> works the same in other windows OK

**Comment by metas-lc** [comment] 2017-05-11 06:55
i noticed that the other tooltips take about 1s to appear, while this one appears instantly. NOK
Can you please put a delay on this one as well?

**Comment by Dunkat** [comment] 2017-05-11 09:07
this one tooltip is an exception and should appears instantly, because user should notice it before click in link

**Comment by cadavre** [comment] 2017-05-11 09:09
Instant appear should ONLY have `n-1` breadcrumb – the one that leads to other page with documents list.

**Comment by metas-mk** [comment] 2017-05-11 10:05
@cadavre @Dunkat I don't think it's an exception, why?
the tooltip for the n-1 breadcrumb just describes what the user will expect when clicking on it, same as in Action menu, Navigation, Inbox and so on. the user will want to read this once/ twice and then knows it forever. why should the tooltip then pop up everytime she/ he clicks on the breadcrumb?
I have a strong feeling that the delay should be harmonized on this n-1 breadcrumb too.

**Comment by cadavre** [comment] 2017-05-11 10:07
I guess the idea behind that was if users clicks it – it will redirect page and loose filters/sorting/ordering/page... As for me keeping it unified (all with delay) is ok. :)

**Comment by metas-mk** [comment] 2017-05-11 10:09
right, perfect, thanks.
then let's go with delay there too.
@Dunkat can u please take over from here ;-)

**Comment by teosarca** [comment] 2017-05-11 13:45
moving it back to Development.

**Comment by metas-lc** [comment] 2017-05-15 12:08
IT
checked again. works fine
there is a delay on every tooltip

**Closed by metas-lc** 2017-05-15 12:08 UTC
Labels: release: candidate, status: integrated, type: enhancement
