### ISSUE TITLE
Sequence of Dropdowns in combined Business Partner Lookups not working

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1923] opened 2018-08-17 13:38 UTC
### Is this a bug or feature request?
Bug
### What is the current behavior?
In combined Business Partner Lookup Fields the implemented behavior sequence is not working anymore. The behavior was depending on 
- multiple locations for a Buisiness Partner
- multiple contacts for a Buisiness Partner
#### Which are the steps to reproduce?
Open Sales Order window and try.
### What is the expected or desired behavior?
Shall work again.

**Comment by metas-lc** [comment] 2018-08-17 13:45
for IT: pls retest https://github.com/metasfresh/metasfresh-webui-frontend/issues/1672

**Comment by siemiatj** [comment] 2018-08-17 17:18
This should already be fixes with my yesterday's changes.

**Comment by metas-dh** [comment] 2018-08-27 09:11
Results of IT1
tested in mf15

Sequence of Dropdowns in combined Business Partner Lookups:
I. business partner: 

a. location:
1. dropdown for location opens: **OK**
2. ship-to location is pre-set, but was not the default ship-to location every time: **NOK**
3. dropdown shows all locations, but not with the default one first every time: **NOK**
4. dropdown shows all locations, also a location that's no ship-to location: **NOK**


b. contact:
1. dropdown for contact opens after setting ship-to location: **OK**
2. no contact  is pre-set, also not the default ship-to contact: **NOK**
3. dropdown shows all contacts, but not with the default ship-to contact first: **NOK**
4. dropdown shows all contacts, also a contact that was no sales contact: **NOK** 
5. when using down arrow for going down the contacts dropdown, the dropdown for location is opened again and changed together with the contact: **NOK**,  http://recordit.co/d0iW0awIec

=> works when using mouse or `Enter`, but when using `Tab` you don't get to the next dropdown, but to invoice partner: **NOK** => #1935



II. invoice partner:

a. location:
1. dropdown only opens when you click actively on e.g. location (when you use `Enter` to confirm the billpartner; when you set the billpartner manually the dropdown opens): OK?
2. default invoice location is pre-set: **OK**
3. dropdown shows only the bill-to locations: **OK**
4. dropdown shows only the bill-to locations, but not with the default one first every time: **NOK**

b. contact:
1. dropdown for contact opens after setting bill-to location: **OK**
2. no contact is pre-set, also not the default one: OK? (not sure this is a new problem related to this task)
3. dropdown shows all contacts, but not with the default bill-to contact first: **NOK**
4. dropdown shows all contacts, also a contact that is no sales contact: **NOK** 

=> works when using mouse or `Enter`, but when using `Tab` you don't get to the next dropdown, but to warehouse:  **NOK** => #1935

**Comment by siemiatj** [comment] 2018-08-28 22:34
I.
a.
2. can't repro, looks good every time here. Any particular business partner this breaks for ?
3. confirmed for `1000010_Machine Parts Ltd.`
4. I'm only displaying on the client what I got from the server, so looks like a backend task. **(backend ?)**
b.
2,3. AD_User_ID is not sent from server with response. **(backend ?)**
4. Data controlled by the backend. **(backend ?)**
5. Can't repro : http://recordit.co/aMQpHdjFTJ

II.
a.
4. Can't repro but I'll assume this happens for the same reason it happens in I.a.3
b.
2,3,4. I don't have data for this with the previous response so can't preselect anything and no default value is given. **(backend ?)**

@teosarca @metas-ts Can you confirm those things are backend realted ?

**Comment by metas-dh** [comment] 2018-09-11 09:35
Results of IT2
tested in mf15

I.
a.
2. ship-to location is pre-set, with the default ship-to location every time: => this works fine as long the default location is not changed, so i guess this is also backend?
3. dropdown shows all locations, with the default one first every time: OK
b.
5. when using down arrow for going down the contacts dropdown, the dropdown for location is opened again and changed together with the contact: could not reproduce this anymore, so i guess it's fine / fixed now
II.
a.
4. dropdown shows only the bill-to locations, with the default one first every time: OK

=> closing this one since the frontend issues were fixed / not reproducable anymore and the remaining issues are backend ones.

@teosarca do we already have a task for the backend issues?

**Closed by metas-dh** 2018-09-11 09:35 UTC
Labels: branch:master, branch:release, priority:high, type:bug
