### ISSUE TITLE
Navigation Menu: Wrong Bookmark entries in Subfolder

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#884] opened 2017-06-13 15:42 UTC
### Type of issue
Bug
### Current behavior
When Bookmarking an entry in a Subfolder, then all entries are shown in Bookmarks.
### Expected behavior
Should only show the bookmarked entries.
### Steps to reproduce
Bookmark The entries as shown in the Screenshot. In the case below only the "Product Category" should be shown.

![image](https://user-images.githubusercontent.com/13365687/27091006-22445a4c-505f-11e7-96b3-a06973cc4d99.png)

**Comment by teosarca** [comment] 2017-06-13 17:00
@metas-mk  can u pls check the API response pls?

**Comment by metas-mk** [comment] 2017-06-13 18:26
Yes sure. Here it is:
![image](https://user-images.githubusercontent.com/13365687/27098064-8f4a768c-5076-11e7-8617-84abe4b97a8d.png)

**Comment by teosarca** [comment] 2017-06-13 19:14
will change it as discussed

**Comment by teosarca** [comment] 2017-06-13 19:25
The only thing that has to be changed on frontend is to display the Menu exactly like the Sitemap looks like.

**Comment by damianprzygodzki** [comment] 2017-06-14 06:50
> The only thing that has to be changed on frontend is to display the Menu exactly like the Sitemap looks like.

So @metas-mk , pls close this task due to duplicate ( #885 ) and the issue is for backend.

**Comment by teosarca** [comment] 2017-06-14 07:26
Note to IT: the backend problem was solved also on this task.
Pls test only the frontend task, when it's ready: https://github.com/metasfresh/metasfresh-webui-frontend/issues/885

**Comment by teosarca** [comment] 2017-06-14 18:29
API provides the correct answer. Closing it.

**Closed by teosarca** 2017-06-14 18:29 UTC
Labels: status:metasfresh-turn, type:bug
