### ISSUE TITLE
Picking Window unselect line in modal overlay

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1199] opened 2017-09-13 14:11 UTC
### Type of issue
Feature request
### Current behavior
When unselecting a line in Picking Window window/540345 sometimes it behaves weird.
### Steps to reproduce
Open window window/540345 and see.
### Expected behavior
a) This is how the Picking window in modal overlay looks like. A line is selected (left side) and the right side shows the Picking Slots.
![image](https://user-images.githubusercontent.com/13365687/30381686-6623221c-989d-11e7-869c-ae3eeb33bb06.png)

b) Now unselect the line w/ [ctrl]+left-mouse-click on line. This is what happens:
![image](https://user-images.githubusercontent.com/13365687/30381750-958ca640-989d-11e7-9cdf-76733e4eeafb.png)

c) Now press left mouse outside table (see image marked w/ A) ). This happens:
![image](https://user-images.githubusercontent.com/13365687/30381798-ba73b228-989d-11e7-8930-6463267ccc15.png)

The cases b) and c) shall not happen. Instead when clicking mouse outside table/ outside right action overlay area (picking slots) OR when unselecting the line in table w/ [ctrl]+mouse-left, then this shall happen:
![image](https://user-images.githubusercontent.com/13365687/30381912-0e4e6b18-989e-11e7-8527-b810fd420d3e.png)

**Comment by ottosichert** [comment] 2017-11-05 22:35
I can't reproduce issue c) on current master a676f2932973d6e63c60b8614bba74a19e8e7b29.

Issue b) still exists, resolving it now

**Comment by metas-dh** [comment] 2017-11-08 15:10
Results of IT1
tested in sp80

* unselecting a selected line in picking window in modal overlay, left side, w/ [ctrl]+left-mouse-click on line: right side disappears, only left side is displayed (see 4th pic above): OK
* press left mouse outside table when a line in picking window in modal overlay, left side, is selected: right side disappears, only left side is displayed (see 4th pic above): OK

however, i could reproduce issue c):
1. select a line in picking window, left side
2. w/ [ctrl]+left-mouse-click, select a 2nd line in picking window, left side
3. w/ [ctrl]+left-mouse-click, unselect the 1st line you selected: right side with picking slots is moved to the right, as in 3rd pic above: NOK

**Comment by metas-dh** [comment] 2017-11-13 14:57
Results of IT2
tested in mf15

retested the above, all working fine: OK

**Closed by metas-dh** 2017-11-13 14:57 UTC
Labels: branch:master, branch:release, type:enhancement
