### ISSUE TITLE
Attributes shall be readonly if the ASI field is readonly

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#319] opened 2017-02-16 10:38 UTC
Case (see the screenshot too)
* ASI field is readonly
* press on the button
* 1. ASI editor popups but you are allowed to edit the attributes => NOK
* 2. click outside of the ASI editor => the popup is not disappearing => NOK

![image](https://cloud.githubusercontent.com/assets/1244701/23017860/92ad7272-f444-11e6-9e48-2d6df29b6d37.png)

**Comment by teosarca** [comment] 2017-02-16 12:36
Also pls apply the same principles to Location editor.

**Comment by teosarca** [comment] 2017-02-16 12:38
btw, if it's hard to implement in frontend,
another option would be frontend to provide "readonly" flag when creating the new ASI....

**Comment by damianprzygodzki** [comment] 2017-02-16 14:41
Okay. So to assume @teosarca , the desired way of working is:

- readonly fields should be not available to edit
- the dropdown should close (which is caused by #294)

**Comment by damianprzygodzki** [comment] 2017-02-16 14:48
But! What i've researched. 

For the 540196/1000003

The ASI field (1000057) is `readonly:false` and any of its fields is readonly. So it is working properly. We are checking the readonly parameter, in the button level and each widget level.

The only issue is that the dropdown is not closing because of validation.

**Comment by damianprzygodzki** [comment] 2017-02-16 14:48
So i am closing this, and reopening #294.

**Closed by damianprzygodzki** 2017-02-16 14:48 UTC
Labels: bug
