### ISSUE TITLE
Incompatible Sock.js versions

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#913] opened 2017-06-19 11:08 UTC
### Type of issue
Bug
### Current behavior
Occurring Incompatibility error w/ Sock.js
### Expected behavior
No errors.
### Steps to reproduce
This happens occasionally. Here in Login.

![image](https://user-images.githubusercontent.com/13365687/27282441-4222561c-54f0-11e7-9be1-2a386d56ad5f.png)

**Comment by tomaszfryc** [comment] 2017-06-20 10:17
I was tested this on chrome, firefox, opera. I can't reproduce this bug. If I notice this behavior, I will check the conditions in which it happened.

**Comment by damianprzygodzki** [comment] 2017-06-20 10:22
@tomaszfryc Yes, me also. Cannot reproduce - but i believe it is not influencing any behavior of application.

Additionally it looks like bug in sockjs-client. The issue is still opened https://github.com/webpack/webpack-dev-server/issues/474. Nothing to do here.

**Comment by damianprzygodzki** [comment] 2017-06-20 10:27
@tomaszfryc Yes, me also. Cannot reproduce - but i believe it is not influencing any behavior of application.

Additionally it looks like version mismatch on api server and frontend app so i've downgraded version to match your API. Maybe it will stop occuring.

**Comment by metas-mk** [comment] 2017-06-20 10:41
@damianprzygodzki 
agree, does not effect the app as far I've seen.
about version api vs. frontend. good point. thanks for the info. does it make sense to rather upgrade API socks to newer version?

**Comment by damianprzygodzki** [comment] 2017-06-20 11:29
I don't know your dependencies on that 1.0.0 version so to make less risky change i've downgraded on frontend. If you want to update that on your side - just let me know.

**Comment by teosarca** [comment] 2017-06-20 22:56
cannot be tested. moving it to done.

**Closed by teosarca** 2017-06-20 22:56 UTC
Labels: branch:master, type:bug
